# Site settings
title: "Software Engineering with Style: Quality Assurance and Continuous Integration"
email: balint@kleri.hu
description: "An introductory workshop to continuous integration with Drupal."
baseurl: ""
url: "http://balintk.com"
twitter_username: balintkleri
github_username:  balintk

# Build settings
markdown: kramdown
permalink: pretty
